apiVersion: xo.90poe.io/v1alpha1
kind: ElasticSearchTemplate
metadata:
  name: example-elasticsearchtemplate
  namespace: zm
spec:
  name: dev_test_test_tmpl
  drop_on_delete: true
  index_patterns:
  - "zm_spm_draft_position_weather_*"
  aliases:
    some_test: {}
    "{index}-alias-for-{gender}":
      filter: |
        {
          "term" : {
            "product" : "Elasticsearch"
          }
        }
      aliases:
      - "zm_spm_draft_position_weather"
  settings:
    number_of_shards: 55
    shards:
      check_on_startup: "false"
    codec: "default"
    number_of_replicas: 3
  mappings: |
    {
      "dynamic": false,
      "_source": {
        "enabled": true
      },
      "properties": {
        "isRead": {
          "type": "boolean",
          "index": true
        },
        "createdAt": {
          "type": "date",
          "index": true
        }
      }
    }
