apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: elasticsearch-operator
rules:
- apiGroups:
  - xo.90poe.io
  resources:
  - elasticsearchindices
  - elasticsearchtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
