apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-objects-operator
  labels:
    app: elasticsearch-objects-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elasticsearch-objects-operator
  template:
    metadata:
      labels:
        name: elasticsearch-objects-operator
        app: elasticsearch-objects-operator
    spec:
      serviceAccountName: elasticsearch-objects-operator
      containers:
        - name: elasticsearch-objects-operator
          # Replace this with the built image name
          image: 90poe/elasticsearch-objects-operator
          command:
          - elasticsearch-objects-operator
          imagePullPolicy: Always
          env:
            - name: ES_URL
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-objects-operator-secret
                  key: ES_URL
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "elasticsearch-objects-operator"
