apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: elasticsearch-operator
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - elasticsearch-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - xo.90poe.io
  resources:
  - elasticsearchindices
  - elasticsearchtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
